enum class ControllerButton {

    //controller buttons
    CONTROLLER_1,
    CONTROLLER_2,
    CONTROLLER_3,
    CONTROLLER_3,
    CONTROLLER_4,
    CONTROLLER_5,
    CONTROLLER_6,
    CONTROLLER_7,
    CONTROLLER_8,
    CONTROLLER_9,
    CONTROLLER_10,
    CONTROLLER_11,
    CONTROLLER_12,
    CONTROLLER_13,
    CONTROLLER_14,
    CONTROLLER_15,
    CONTROLLER_16,
    CONTROLLER_17,
    CONTROLLER_18,
    CONTROLLER_19,
    CONTROLLER_20
};