enum class ControllerAxis {

    //controller buttons
    CONTROLLER_LEFT_VERICAL_AXIS,
    CONTROLLER_LEFT_HORIZONTAL_AXIS,

    CONTROLLER_RIGHT_VERICAL_AXIS,
    CONTROLLER_RIGHT_HORIZONTAL_AXIS,

    CONTROLLER_LEFT_TRIGGER_AXIS,
    CONTROLLER_RIGHT_TRIGGER_AXIS,

    DEFAULT
};