enum class ControllerAxis {

    //controller buttons
    CONTROLLER_LEFT_VERICAL_AXIS,
    CONTROLLER_LEFT_HORIZONTAL_AXIS,
    CONTROLLER_RIGHT_VERICAL_AXIS,
    CONTROLLER_RIGHT_HORIZONTALL_AXIS,

    CONTROLLER_3_VERICAL_AXIS,
    CONTROLLER_3_HORIZONTALL_AXIS,

    CONTROLLER_4_VERICAL_AXIS,
    CONTROLLER_4_HORIZONTALL_AXIS,

    CONTROLLER_5_VERICAL_AXIS,
    CONTROLLER_5_HORIZONTALL_AXIS,

    CONTROLLER_6_VERICAL_AXIS,
    CONTROLLER_6_HORIZONTALL_AXIS,

    CONTROLLER_7_VERICAL_AXIS,
    CONTROLLER_7_HORIZONTALL_AXIS,

    CONTROLLER_8_VERICAL_AXIS,
    CONTROLLER_8_HORIZONTALL_AXIS,

    CONTROLLER_9_VERICAL_AXIS,
    CONTROLLER_9_HORIZONTALL_AXIS,

    CONTROLLER_10_VERICAL_AXIS,
    CONTROLLER_10_HORIZONTALL_AXIS,
};